version: 1.0.{build}

platform: Any CPU

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\africastalking

# set clone depth
clone_depth: 5  

configuration: Release

skip_commits:
  files:
    - ScreenShots/*
    - '*.yml' 
    - '.gitignore'
    - 'README.md'

build:
  parallel: true
  project: AfricasTalkingCS.sln
  verbosity: detailed

after_build:

- ps: >-

    .\build\build.cmd 
     
# on successful build
on_success:
  - echo Success

# on build failure
on_failure:
  - echo Error occurred

# after build failure or success
on_finish:
  - echo Done!   